language: python
sudo: false
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"
  - "pypy3"
env:
  - LC_ALL="en_US.utf-8"
  - LC_ALL="en_US.ascii"
branches:
  only:
    - develop
install:
  - python -c "import sys; print(sys.getfilesystemencoding())"
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
script:
  - check-manifest
  - flake8
  - pytest
  - python tests/test_pathlib2_with_py2_unicode_literals.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
