language: python
sudo: false
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"
  - "pypy3"
env:
  - LC_ALL="en_US.utf-8"
  - LC_ALL="en_US.ascii"
branches:
  only:
    - develop
install:
  - python -c "import sys; print(sys.getfilesystemencoding())"
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - pip install tox-travis
script:
  - check-manifest
  # ignore defaults, plus F821 (undefined names), F401 (unused imports), E402 (imports not at top of file)
  - flake8 --ignore=E121,E123,E126,E226,E24,E704,F821,F401,E402 --statistics --exit-zero
  - tox
after_success:
  - bash <(curl -s https://codecov.io/bash)
